#!/bin/sh

if [ $# -ne 2 ]; then
    echo "Usage: copy_tensorflow_headers <tensorflow-git-path> <teeworlds-tmlp-git-path>"
    exit 1
fi

SRC="$(readlink -f "$1")"
OBJ_DST="$(readlink -f "$2")/other/tensorflow"
DST="$OBJ_DST/include"

rm -rf "$OBJ_DST"
mkdir -p "$DST"

# Headers
cd "$SRC"
find "tensorflow" -type f -name '*.h' -exec cp --parents \{\} "$DST" \;
cd "$SRC/bazel-genfiles"
find "tensorflow" -type f -name '*.h' -exec cp --parents \{\} "$DST" \;
cd "$SRC/bazel-tensorflow/external/com_google_absl"
find -L "absl" -type f \( -name '*.h' -o -name '*.inc' \) -exec cp --parents \{\} "$DST" \;
cd "$SRC"
find "third_party/eigen3/unsupported/Eigen" -type f -exec cp --parents \{\} "$DST" \;
cd "$SRC/bazel-tensorflow/external/eigen_archive"
find "unsupported/Eigen" -type f -exec cp --parents \{\} "$DST" \;
find -L "Eigen" -type f -exec cp --parents \{\} "$DST" \;
cd "$SRC/bazel-tensorflow/external/protobuf_archive/src"
find "google" -type f \( -name '*.h' -o -name '*.inc' \) -exec cp --parents \{\} "$DST" \;

# Shared objects
cp "$SRC/bazel-bin/tensorflow/libtensorflow_cc.so.1" "$OBJ_DST"
cp "$SRC/bazel-bin/tensorflow/libtensorflow_framework.so.1" "$OBJ_DST"
